app/controllers/application_controller.rb, app/controllers/contractor_requests_controller.rb, app/controllers/labor_requests_controller.rb, app/controllers/staff_requests_controller.rb, app/models/user.rb, app/policies/personnel_request_policy.rb, app/views/shared/_index_action_buttons.erb, app/views/shared/_show_action_buttons.erb, app/views/shared/_table_action_buttons.erb, test/integration/contractor_requests_edit_test.rb, test/integration/contractor_requests_index_test.rb, test/integration/labor_requests_edit_test.rb, test/integration/labor_requests_index_test.rb, test/integration/personnel_request_policy_integration_test.rb, test/integration/staff_requests_edit_test.rb, test/integration/staff_requests_index_test.rb, test/models/user_test.rb, test/policies/personnel_request_policy_scope_test.rb, test/policies/personnel_request_policy_test.rb, test/test_helper.rb
Limited create, read, update, and delete functions for personnel requests, based on user roles using Pundit.
Modifications were made to both controller actions (so that even direct URL requests would be sent to a "Not Authorized" page, if the user did not have the appropriate permissions, and to the suppression of GUI elements, such as the "New" or "Edit" button, that would lead to a "Not Authorized" page.
Policy is defined in the app/policies/personnel_request_policy.rb file.
https://issues.umd.edu/browse/LIBITD-439
=> LIBITD-439. Restrict CRUD functions on personnel requests based on user roles

Gemfile.lock
https://issues.umd.edu/browse/LIBITD-489
=> LIBITD-489. Updated umd_lib_style gem reference to pull in logo on left.

Gemfile.lock, app/assets/stylesheets/application.scss
Removed the grid-float-breakpoint setting.
The grid-float-breakpoint in umd_lib_style has a sensible default
(1200px) for this application, so there is no need to set it in both
places.
If the default grid-float-breakpoint setting ever becomes unsuitable,
it can be overridden by adding the setting to this file.
https://issues.umd.edu/browse/LIBITD-498
=> LIBITD-498. Implement improved umd_lib_style from mockup

.gitignore, app/controllers/contractor_requests_controller.rb, app/controllers/labor_requests_controller.rb, app/controllers/personnel_request_controller.rb, app/controllers/staff_requests_controller.rb, app/policies/personnel_request_policy.rb, app/views/contractor_requests/_form.html.erb, app/views/labor_requests/_form.html.erb, app/views/staff_requests/_form.html.erb, test/controllers/contractor_requests_controller_test.rb, test/controllers/labor_requests_controller_test.rb, test/controllers/staff_requests_controller_test.rb, test/fixtures/contractor_requests.yml, test/fixtures/labor_requests.yml, test/fixtures/staff_requests.yml, test/integration/contractor_requests_edit_test.rb, test/integration/contractor_requests_index_test.rb, test/integration/labor_requests_edit_test.rb, test/integration/labor_requests_index_test.rb, test/integration/personnel_request_policy_integration_test.rb, test/integration/personnel_requests_test_helper.rb, test/integration/staff_requests_edit_test.rb, test/integration/staff_requests_index_test.rb, test/policies/personnel_request_policy_scope_test.rb, test/policies/personnel_request_policy_test.rb, test/test_helper.rb
Limits the entries in the "Department" and "Unit" drop-downs for personnel requests, based on the user's roles, and role cutoffs.
Selectable departments/units are controlled by the "selectable_departments" and "selectable_units" methods in PersonnelRequestPolicy.
Departments and units for the drop-downs are passed to the views in the "@selectable_departments" and "@selectable_units" variables. The variables are assigned by the "assign_selectable_departments_and_units" method in the PersonnelRequestController module.
Also added a "with_temp_user" closure to test_helper.rb, which eases creation of temporary users with particular roles.
https://issues.umd.edu/browse/LIBITD-441
=> LIBITD-441. Limit "Department" and "Unit" based on role permissions

app/controllers/personnel_request_controller.rb
PG has an issue with negative LIMIT statements. Remove the negative
per_page being used for Excel exports
https://issues.umd.edu/browse/LIBITD-513
=> LIBITD-513 remove negative LIMIT for per_page

app/models/contractor_request.rb, app/models/labor_request.rb, app/models/staff_request.rb, app/views/contractor_requests/show.html.erb, app/views/labor_requests/show.html.erb, app/views/staff_requests/show.html.erb, config/locales/en.yml, test/integration/contractor_requests_edit_test.rb, test/integration/contractor_requests_index_test.rb, test/integration/contractor_requests_show_test.rb, test/integration/labor_requests_edit_test.rb, test/integration/labor_requests_index_test.rb, test/integration/labor_requests_show_test.rb, test/integration/personnel_requests_test_helper.rb, test/integration/staff_requests_edit_test.rb, test/integration/staff_requests_index_test.rb, test/integration/staff_requests_show_test.rb
Modified "Nonop funds" and "Nonop source" to use an internationalized label, and then changed
the i18n text.
https://issues.umd.edu/browse/LIBITD-484
=> LIBITD-484. Change column heading "Nonop funds" to "Gift/Other Funds"

Gemfile, Gemfile.lock, test/test_helper.rb
Added simplecov-rcov to enable Jenkins to parse coverage
https://issues.umd.edu/browse/LIBITD-499
=> LIBITD-499. Integrate simplecov test coverage reports into Jenkins

app/controllers/personnel_request_controller.rb, test/controllers/labor_requests_controller_test.rb
Fixed a bug where the Excel spreadsheet generated from the "Export"
button would not contain any records if selected from the second
page.
Modified "scope_records" method so that pagination would not be
used with the 'xlsx' format.
https://issues.umd.edu/browse/LIBITD-534
=> LIBITD-534. Fixed "Export" returning no records from second page.

app/views/users/_form.html.erb
Field can only be filled in when creating a user. If the user already has an id field (i.e., it's primary key in the database) then set the cas_directory_id field to readonly.
https://issues.umd.edu/browse/LIBITD-556
=> LIBITD-556. Made CAS Directory ID field readonly.

app/assets/javascripts/custom.js, app/helpers/application_helper.rb
Switched from the simple hover title on the help icon to a bootstrap button which triggers a popover containing the help text.
https://issues.umd.edu/browse/LIBITD-548
=> LIBITD-548. Added popovers for descriptor help text.

Gemfile, Gemfile.lock, app/controllers/contractor_requests_controller.rb, app/controllers/labor_requests_controller.rb, app/controllers/staff_requests_controller.rb, app/views/contractor_requests/_form.html.erb, app/views/labor_requests/_form.html.erb, app/views/staff_requests/_form.html.erb
Convert the localized number formats with commas into non-localized numbers that ActiveRecord can handle. Previously, it was truncating at the comma since it was not a digit or a decimal point. Also forced the thousands delimiter to comma for the currency fields on the request forms.
https://issues.umd.edu/browse/LIBITD-552
=> LIBITD-552. Use delocalize gem for handling numbers.

app/assets/stylesheets/application.scss, app/views/contractor_requests/_form.html.erb, app/views/labor_requests/_form.html.erb, app/views/staff_requests/_form.html.erb
This adds a small "*" to labels of fields required in a personel request.
The forms aren't using the helpers to show if a attr is requiest, so this manually
adds the "required" to the class.
https://issues.umd.edu/browse/LIBITD-559
=> LIBITD-559. Adding required field to request forms

app/assets/javascripts/custom.js
Turbolinks mucks about with the page loading so that document.ready is only fired when
the user visits the page the first time.
We should bind to document.ready and turbolinks:load events.
https://issues.umd.edu/browse/LIBITD-623
=> LIBITD-623 Bind popover() to turbolinks:load

app/assets/javascripts/custom.js, app/views/labor_requests/_form.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml
This adds more to help documents, moves it to the far right of the nav bar and makes
it a drop-down. Also includes link to document in descriptor of number of weeks
https://issues.umd.edu/browse/LIBITD-624
=> LIBITD-624 Add more help documents

app/assets/stylesheets/custom.css.scss, app/models/contractor_request.rb, app/models/labor_request.rb, app/models/staff_request.rb, app/views/contractor_requests/_form.html.erb, app/views/labor_requests/_form.html.erb, app/views/staff_requests/_form.html.erb, test/models/contractor_request_test.rb, test/models/labor_request_test.rb, test/models/staff_request_test.rb
Made "Justification" field required in personnel requests.
Added CSS to style "Justification" textarea with a red border, when
there is a validation error with the field. This is really just a
workaround, until LIBITD-659.
https://issues.umd.edu/browse/LIBITD-658
=> LIBITD-658. Made "Justification" field required in personnel requests

app/assets/stylesheets/custom.css.scss, app/models/contractor_request.rb, app/models/labor_request.rb, app/models/staff_request.rb, app/views/contractor_requests/_form.html.erb, app/views/labor_requests/_form.html.erb, app/views/staff_requests/_form.html.erb, test/models/contractor_request_test.rb, test/models/labor_request_test.rb, test/models/staff_request_test.rb
Made "Justification" field required in personnel requests.
Added CSS to style "Justification" textarea with a red border, when
there is a validation error with the field. This is really just a
workaround, until LIBITD-659.
https://issues.umd.edu/browse/LIBITD-658
=> LIBITD-658. Made "Justification" field required in personnel requests 

Gemfile, Gemfile.lock, app/controllers/reports_controller.rb, app/jobs/report_job.rb, app/models/concerns/reportable.rb, app/models/reports/labor_requests_cost_summary_report.rb, app/views/reports/_labor_requests_cost_summary_report_form.html.erb, app/views/reports/show.html.erb, app/views/shared/labor_requests_cost_summary.axlsx, config/initializers/axlsx_styles.rb, config/locales/en.yml, db/migrate/20170118160334_add_status_message_to_report.rb, db/schema.rb, docs/Reports.md, lib/tasks/reports/labor_requests_cost_summary_report_test.rake, test/integration/reports/labor_requests_cost_summary_report_test.rb, test/models/reports/labor_requests_cost_summary_report_test.rb
Modified "Labor requests cost summary" report with the following changes:
1) Added additional worksheets for each division
2) Added styling
3) Added "Review Status" input parameters, to enable user to choose the review statuses that should be represented in the report.
4) Added a simple framework for validating report paramaters, and displaying errors.
https://issues.umd.edu/browse/LIBITD-537
=> LIBITD-537. Expand Labor requests cost summary report to include Division summaries

app/views/contractor_requests/_form.html.erb, app/views/contractor_requests/show.html.erb, app/views/labor_requests/_form.html.erb, app/views/labor_requests/show.html.erb, app/views/shared/_form_admin_use_only.erb, app/views/shared/_show_admin_use_only.erb, app/views/staff_requests/_form.html.erb, app/views/staff_requests/show.html.erb
Added an "Admin Use Only" panel that contains the "Review Status" and
"Review Comment" field.
Moved into a partial, and then updated all the show/edit personnel
request views.
https://issues.umd.edu/browse/LIBITD-562
=> LIBITD-562. Added "Admin Use Only" panel to show/edit pages

app/models/reports/staff_requests_cost_summary_report.rb, db/seeds.rb, lib/tasks/upgrade/libitd779.rake, test/fixtures/employee_types.yml, test/models/reports/staff_requests_cost_summary_report_test.rb
The code for employee type "Non-exempt" seems to be either "Nex" or "NEX". This
sets the convention to be NEX ( app upcase ), which is similar to all the other
employee type codes.
https://issues.umd.edu/browse/LIBITD-779
=> LIBITD-779 Fixes Employee Type "Non-Exempt" code

app/policies/personnel_request_policy.rb, db/migrate/20170227175630_add_fiscal_rollover.rb, db/schema.rb
Changes the migration to explicitly build the archive table fields rather than
using SQL to copy the tables ( seems to be some problems depending on RDBMS )
Also changes the checking if the AR model is an "Archived" model. Minitest
seems to stub some class methods ( e.g.  .class_name ) that act rather
odd and seem platform dependant. Changes to use a different method.
https://issues.umd.edu/browse/LIBITD-749
=> LIBITD-749 Change migration and checking of model name

app/assets/stylesheets/home.scss, app/models/organization.rb, app/models/user.rb, app/views/organizations/_form.erb, app/views/organizations/edit.html.erb, app/views/organizations/index.html.erb, app/views/organizations/show.html.erb, app/views/users/_form.html.erb
This tries to make it more clean in UI what the current roles are in
relation to orgs and users. User detail pages show what orgs are
included in the user's roles ( all orgs via the hierachy ).
The same is done for orgs, with org detail pages showing what users have
access to the org going up the ancestor chain.
The goal is to make it more clear what users have access to what orgs.
Also adds some UI elements to the org page to show what the status and
types are.
=> LIBITD-925 Make more obvious what user and org permissions are

lib/counter_cache_manager.rb, lib/tasks/archive_current_records.rake, lib/tasks/sample_data.rake
This ensures the counter cache is reset after records have been moved to
the archive. The reset task is run after the archive task.
https://issues.umd.edu/browse/LIBITD-976
=> LIBITD-976 Ensure that the counter cache is reset after archiving

lib/record_migrator.rb, lib/tasks/dump_data.rake
This adds a json exporter to dump records from 1.2.0 in preperation to
an update to 2.0
https://issues.umd.edu/browse/LIBITD-977
=> LIBITD-977 Add an exporter to 1.2.0 for migration

Gemfile, Gemfile.lock, config/application.rb
Pinned axlsx version to 2.0.1, as that more closely matches what was in
v1.2.0 (which used v2.0.0).
Unpinned rubyzip version, as axlsx needs it to be "~> 1.0.0".
Pinned "roo" version to 1.13.2, as that matches what was in v1.2.0.
Added subdirectories of "app/models" directory to the autoload path. This
was needed for the "report" tests to find the "report" models.
https://issues.umd.edu/browse/LIBITD-999
=> LIBITD-999. Fixed broken tests on feature/LIBITD-749 branch.

app/controllers/ping_controller.rb, config/routes.rb, test/controllers/ping_controller_test.rb
The "ping" controller provides a "/ping" resource that Icinga can
access without having to perform CAS authentication to verify that the
application is running.
https://issues.umd.edu/browse/LIBITD-1002
=> LIBITD-1002. Restored "ping" controller for Icinga network monitoring

Gemfile, Gemfile.lock
The Annual Staffing Request application is currently using
Postgres v8.4, and v0.18.4 is the last version of the
"pg" gem that supported Postgres v8.4.
This should fix the following warnings which were seen when running
database Rake tasks on the "dev" server:
```
> rake db:migrate RAILS_ENV=production
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.
You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
Called from /apps/services/annual-staffing-request/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
```
https://issues.umd.edu/browse/LIBITD-1005
=> LIBITD-1005. Pinned "pg" gem to v0.18.4

Gemfile, app/models/request.rb, test/models/labor_request_test.rb
Previously the justification length validation was set to only be
checked during save, not edit ( in case there are existing records
created prior to the new rule ). This changes it to check all records
except Archived records.
https://issues.umd.edu/browse/LIBITD-1004
=> LIBITD-1004 Make sure justification length is enfored request edits

app/models/concerns/resettable.rb, app/models/organization.rb
The way the class loading was working out on the db:migrate it was
resetting some constants when it lazy loaded the Organization class. This moves the
constants into the concern, so those pesky warning messages should go
away.
https://issues.umd.edu/browse/LIBITD-994
=> LIBITD-994 Move a couple of constants into the concern

config/initializers/fiscali.rb
When archiving records, we want to use the 'forward year' ( eg. fiscal
year 2017-2018 == FY18 )
https://issues.umd.edu/browse/LIBITD-1024
=> LIBITD-1024 Use 'forward year' for tagging Fiscal Year

app/assets/javascripts/app.es6, app/assets/javascripts/application.js, app/assets/javascripts/require_tooltip.es6
This makes the required label hover use the BS tooltip, rather than
html5.
https://issues.umd.edu/browse/LIBITD-1016
=> LIBITD-1016 Make "required" hover use tooltip

test/test_helper.rb
It looks like some platforms ( i.e. Jenkins ) don't like the resize method, so this moves
the default screensize to an argument passed directly to chromedriver on
initialization.
https://issues.umd.edu/browse/LIBITD-1065
=> LIBITD-1065 Set the default screensize for chromedriver

app/policies/request_policy.rb, test/policies/request_policy_scope_test.rb
Request policy was not checking the unit id of the record for user
permissions on the edit permissions check. We should check if the user
has an organization id that's either the records organization_id or
unit_id.
https://issues.umd.edu/browse/LIBITD-1081
LIBITD-1081 Ensure policy show is set for unit user
(cherry picked from commit c6fbe855beaed40469e0f8cb55e29bee5b15a662)
=> LIBITD-1081 Allow unit users to edit unit records

README.md, lib/tasks/db.rake, lib/tasks/reset_counters.rake
This updates the README to add some instuctions on the rake tasks.
Also makes sure the reset_counter_cache task loads the environment
before running ( since eager_load is called )
https://issues.umd.edu/browse/LIBITD-979
=> LIBITD-979 Update the README and minor change to reset_counters task

Gemfile, Gemfile.lock
Updated the "axlsx" and associated "rubyzip" gem to address
vulnerable version of "rubyzip". Needed to update "axlsx" gem to
"3.0.0.pre" version, because previous version had a gemspec file that
locked rubyzip to v1.1.x.
https://issues.umd.edu/browse/LIBITD-1285
=> LIBITD-1285. Updated gems to fix security vulnerabilities

app/helpers/request_helper.rb, app/helpers/xlsx_helper.rb, app/views/requests/index.xlsx.axlsx, test/controllers/labor_requests_controller_test.rb
Fixes an issue where the currency fields in the Excel spreadsheet for
exported personnel requests were displaying as a general text field,
instead of a more specific numeric field.
Modified index.xlsx.axlsx to use workbook-defined styles, as in
other Axlsx views.
Modified XlsxHelper to use CURRENCY_FIELDS and LENGTHY_FIELDS constants
directly (as is done in other places in the code), instead of delegating
to methods in the RequestHelper module. Fixed the "field_formats" method
to actually return a format, instead of width. Also flipped the order of
the return values in the "formats_and_widths" method because that was
what seemed to be expected in other parts of the code (and the order
matches the method name).
Removed unused methods in the RequestHelper module …
=> LIBITD-1275. Fix Excel formatting for personnel request currency fields

app/policies/request_policy.rb, test/system/unit_user_test.rb
The request policy can fail on new records because it's assuming the
record has organizations ( new records do not ). If the record is dirty,
allow editing as long as the user has orgs to use.
https://issues.umd.edu/browse/LIBITD-1290
=> LIBITD-1290 Allow edits on new records in policy

app/controllers/concerns/personnel_request_controller.rb, app/models/archived_contractor_request.rb, app/models/contractor_request.rb, app/models/request.rb, app/views/requests/_contractor_request_form.html.erb, test/models/contractor_request_test.rb, test/system/archived_contractor_request_test.rb
This adds a mapping for when a Contractor request is "spawned" from an
archived request. Since the Faculty Contract has the Faculty Contractor
employee_type was changed, this needs to be mapped to PTK Contractor.
https://issues.umd.edu/browse/LIBITD-1298?
=> LIBITD-1298 Map to PTK Contractor when spawning
