umd-lib/annual-staffing-request

- Gemfile
- Gemfile.lock
- app/controllers/contractor_requests_controller.rb
- app/controllers/labor_requests_controller.rb
- app/controllers/staff_requests_controller.rb
- app/views/contractor_requests/index.html.erb
- app/views/departments/index.html.erb
- app/views/divisions/index.html.erb
- app/views/employee_categories/index.html.erb
- app/views/employee_types/index.html.erb
- app/views/labor_requests/index.html.erb
- app/views/request_types/index.html.erb
- app/views/shared/_index_action_buttons.erb
- app/views/staff_requests/index.html.erb
- app/views/subdepartments/index.html.erb
- lib/tasks/sample_data.rake
- test/fixtures/contractor_requests.yml
- test/fixtures/labor_requests.yml
- test/fixtures/staff_requests.yml
- test/fixtures/subdepartments.yml
- test/integration/contractor_requests_index_test.rb
- test/integration/labor_requests_index_test.rb
- test/integration/staff_requests_index_test.rb
Added pagination bars to the top and bottom of the following pages:
* http://127.0.0.1:3000/labor_requests
* http://127.0.0.1:3000/staff_requests
* http://127.0.0.1:3000/contractor_requests
Note: Did not add pagination to ther pages (Divisions, Departments, Subdepartments, etc.) because they seemed unlikely to grow to a point where pagination would be needed.
https://issues.umd.edu/browse/LIBITD-408
> LIBITD-408. Added pagination to request index pages

- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/application_controller.rb
- config/database.yml
- config/environment.rb
- env_example
- test/test_helper.rb
* Enabled CAS authentication
* Added "dotenv-rails" gem to enable environment variables to be provided via a .env file
* Added Postgres gem
https://issues.umd.edu/browse/LIBITD-421
> LIBITD-421. Prepare Annual Staffing Request application for production

- Gemfile
Production instances may want to generate sample data.
https://issues.umd.edu/browse/LIBITD-421
> LIBITD-421. Moved "faker" gem to be usable in production

- README.md
https://issues.umd.edu/browse/LIBITD-439
> LIBITD-439. Added permission matrix to README.md

- .rubocop.yml
- Gemfile.lock
- app/assets/stylesheets/custom.css.scss
- app/controllers/impersonate_controller.rb
- app/controllers/users_controller.rb
- app/helpers/cas_helper.rb
- app/policies/impersonate_policy.rb
- app/views/impersonate/index.html.erb
- app/views/layouts/_impersonate.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- test/controllers/impersonate_controller_test.rb
- test/helpers/cas_helper_test.rb
- test/integration/impersonate_index_test.rb
- test/integration/static_pages_index_test.rb
https://issues.umd.edu/browse/LIBITD-432
> LIBITD-432. Provide ability to "impersonate" another user

- app/models/labor_request.rb
- app/views/labor_requests/index.html.erb
- app/views/labor_requests/show.html.erb
- lib/tasks/sample_data.rake
- test/integration/contractor_requests_edit_test.rb
- test/integration/contractor_requests_index_test.rb
- test/integration/contractor_requests_show_test.rb
- test/integration/labor_requests_edit_test.rb
- test/integration/labor_requests_index_test.rb
- test/integration/labor_requests_show_test.rb
- test/integration/personnel_request_index_test_helper.rb
- test/integration/staff_requests_edit_test.rb
- test/integration/staff_requests_index_test.rb
- test/integration/staff_requests_show_test.rb
- test/models/labor_request_test.rb
- test/test_helper.rb
https://issues.umd.edu/browse/LIBITD-442
> LIBITD-442. Provide "Annual Cost" column in "Labor and Assistance" requests

- app/views/contractor_requests/index.html.erb
- app/views/labor_requests/index.html.erb
- app/views/shared/_table_action_buttons_header.erb
- app/views/staff_requests/index.html.erb
- config/initializers/form_helper.rb
- test/fixtures/roles.yml
- test/fixtures/users.yml
- test/integration/labor_requests_index_test.rb
https://issues.umd.edu/browse/LIBITD-443
> LIBITD-443 add multicolumn sorting

- app/controllers/impersonate_controller.rb
- app/policies/impersonate_policy.rb
- app/views/impersonate/index.html.erb
- app/views/layouts/application.html.erb
- test/controllers/impersonate_controller_test.rb
- test/integration/impersonate_index_test.rb
- test/policies/impersonate_policy_test.rb
- test/test_helper.rb
https://issues.umd.edu/browse/LIBITD-495
> LIBITD-495. Admins should not impersonate themselves or other admins

- app/controllers/review_statuses_controller.rb
- app/models/contractor_request.rb
- app/models/labor_request.rb
- app/models/review_status.rb
- app/models/staff_request.rb
- app/views/contractor_requests/index.html.erb
- app/views/labor_requests/index.html.erb
- app/views/review_statuses/_form.html.erb
- app/views/review_statuses/_review_status.json.jbuilder
- app/views/review_statuses/edit.html.erb
- app/views/review_statuses/index.html.erb
- app/views/review_statuses/show.html.erb
- app/views/staff_requests/index.html.erb
- db/migrate/20160923195155_add_code_to_review_statuses.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/sample_data.rake
- test/controllers/contractor_requests_controller_test.rb
- test/controllers/labor_requests_controller_test.rb
- test/controllers/review_statuses_controller_test.rb
- test/controllers/staff_requests_controller_test.rb
- test/fixtures/contractor_requests.yml
- test/fixtures/labor_requests.yml
- test/fixtures/review_statuses.yml
- test/fixtures/staff_requests.yml
- test/integration/contractor_requests_index_test.rb
- test/integration/labor_requests_index_test.rb
- test/integration/staff_requests_index_test.rb
- test/models/review_status_test.rb
https://issues.umd.edu/browse/LIBITD-496
> LIBITD-496. "Under Review" should be default status of all requests, but not displayed

- lib/tasks/upgrade/libitd496.rake
https://issues.umd.edu/browse/LIBITD-508
> LIBITD-508. Added Rake upgrade task for LIBITD-496

- lib/tasks/upgrade/libitd496.rake
https://issues.umd.edu/browse/LIBITD-508
> LIBITD-508. Added "Review Status" default for Staff and Contractor

- app/assets/stylesheets/custom.css.scss
- app/helpers/application_helper.rb
- app/views/contractor_requests/_form.html.erb
- app/views/labor_requests/_form.html.erb
- app/views/staff_requests/_form.html.erb
- config/locales/en.yml
- test/helpers/application_helper_test.rb
- test/integration/contractor_requests_edit_test.rb
- test/integration/labor_requests_edit_test.rb
- test/integration/staff_requests_edit_test.rb
https://issues.umd.edu/browse/LIBITD-481
> LIBITD-481. Provide "Help" descriptors on fields

- app/helpers/personnel_requests_helper.rb
- app/views/shared/index.xlsx.axlsx
- test/integration/contractor_requests_index_test.rb
- test/integration/labor_requests_index_test.rb
- test/integration/staff_requests_index_test.rb
This adds columns for all fields in excel exports
https://issues.umd.edu/browse/LIBITD-515
> LIBITD-515 include all fields in excel exports

- app/controllers/reports_controller.rb
- app/models/report.rb
- app/views/reports/index.html.erb
- test/controllers/reports_controller_test.rb
- test/fixtures/reports.yml
- test/fixtures/roles.yml
- test/fixtures/users.yml
- test/integration/reports_flow_test.rb
- test/integration/reports_index_test.rb
- test/models/report_test.rb
https://issues.umd.edu/browse/LIBITD-520
> LIBITD-520. "Creator" field does not sort on "Reports" page

- config/locales/en.yml
https://issues.umd.edu/browse/LIBITD-529
> LIBITD-529. Fixed mislabeled "Department" column.

- app/helpers/personnel_requests_helper.rb
- app/views/shared/index.xlsx.axlsx
- test/integration/contractor_requests_index_test.rb
This adds currency formatting to the excel exports. It ditched the standard currency
view helper, which messes up sorting in spreadsheets.
> LIBITD-506 Add currency formating to excel exports

- app/controllers/reports_controller.rb
Changed "Request type" to "Report".
https://issues.umd.edu/browse/LIBITD-530
> LIBITD-530. Fixed report record flash message.

- app/controllers/contractor_requests_controller.rb
- app/controllers/departments_controller.rb
- app/controllers/divisions_controller.rb
- app/controllers/employee_categories_controller.rb
- app/controllers/employee_types_controller.rb
- app/controllers/labor_requests_controller.rb
- app/controllers/reports_controller.rb
- app/controllers/request_types_controller.rb
- app/controllers/review_statuses_controller.rb
- app/controllers/role_cutoffs_controller.rb
- app/controllers/role_types_controller.rb
- app/controllers/roles_controller.rb
- app/controllers/staff_requests_controller.rb
- app/controllers/units_controller.rb
- app/controllers/users_controller.rb
Message is "{record type} for {description} was successfully {operation}".
https://issues.umd.edu/browse/LIBITD-527
> LIBITD-527. Added "for {description}" to all record flash messages.

- db/seeds.rb
- lib/tasks/upgrade/libitd551.rake
- test/fixtures/departments.yml
Updated the database seed file and the test fixture data. Added a rake task (upgrade:libitd551) that converts an existing department name.
https://issues.umd.edu/browse/LIBITD-551
> LIBITD-551. Changed "Collections Development" to "Collection".

- .rubocop.yml
- app/controllers/contractor_requests_controller.rb
- app/controllers/departments_controller.rb
- app/controllers/labor_requests_controller.rb
- app/controllers/reports_controller.rb
- app/controllers/role_cutoffs_controller.rb
- app/controllers/role_types_controller.rb
- app/controllers/roles_controller.rb
- app/controllers/staff_requests_controller.rb
- app/controllers/units_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/policies/personnel_request_policy.rb
- app/views/static_pages/index.html.erb
- config/initializers/pundit.rb
- test/integration/personnel_request_policy_integration_test.rb
There was a problem with permissions check if a user has certain permissions.
0) user with unit level permissions adding a record with a blank unit
1) users with different levels of permissions adding records with no department
This tries to catch if a user is trying to add to a dept or unit they don't have access
to. And error is raised and the view should tell the user in the edit form.
https://issues.umd.edu/browse/LIBITD-554
> LIBITD-554 Fix permissions check for certain situations

- app/models/labor_request.rb
- test/models/labor_request_test.rb
https://issues.umd.edu/browse/LIBITD-550
> LIBITD-550. Include number of positions in annual cost calculation.

- app/assets/stylesheets/custom.css.scss
- app/models/staff_request.rb
- app/views/staff_requests/_form.html.erb
- db/migrate/20161026154824_add_employee_name_to_staff_requests.rb
- db/schema.rb
Field is required if the staff request type is a pay adjustment. Otherwise it is optional.
https://issues.umd.edu/browse/LIBITD-555
> LIBITD-555. Add employee_name field to staff requests.

- config/locales/en.yml
https://issues.umd.edu/browse/LIBITD-549
> LIBITD-549. Added descriptors for non-op fund fields.

- app/models/staff_request.rb
- db/seeds.rb
- test/fixtures/request_types.yml
- test/models/staff_request_test.rb
This adds a backfill option to the staff request request type.
https://issues.umd.edu/browse/LIBITD-553
> LIBITD-553 Add backfill to staff request request type

- db/seeds.rb
- lib/tasks/upgrade/libitd531-532.rake
- test/fixtures/employee_types.yml
Changes the codes in the fixtures and adds a rake task to update the db.
ContFac CFAC
Ex EX
Fac FAC
FAC-Hrly FHRLY
Nex NEX
Student STUD
https://issues.umd.edu/browse/LIBITD-532
> LIBITD-532 Change some employee type codes

- app/views/layouts/application.html.erb
This adds a link to pdf that has help documentation
https://issues.umd.edu/browse/LIBITD-557
> LIBITD-557

- app/assets/stylesheets/static_pages.scss
- app/views/static_pages/index.html.erb
- config/locales/en.yml
Add some descriptions to the homepage
https://issues.umd.edu/browse/LIBITD-592
> LIBITD-592

- app/assets/stylesheets/users.scss
- app/controllers/users_controller.rb
- app/helpers/cas_helper.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/users/logout.html.erb
- config/routes.rb
- test/integration/logout_test.rb
This adds a page to sign out. Session is reset and users are informed to either
logout of CAS or close their browser.
> LIBITD-558 Add a sign out page

- app/assets/stylesheets/static_pages.scss
Make the links bold.
https://issues.umd.edu/browse/LIBITD-601
> LIBITD-601 Make request type links bold on home page.

- Gemfile
- Gemfile.lock
https://issues.umd.edu/browse/LIBITD-700
> LIBITD-700. Updated "umd_lib_style" gem to v0.2.0

- app/helpers/application_helper.rb
- app/helpers/personnel_requests_helper.rb
- app/views/shared/index.xlsx.axlsx
- config/initializers/axlsx_styles.rb
- test/helpers/personnel_requests_helper_test.rb
- Rearranged columns as per issue
- Set column widths for large text fields
- Added formatting for worksheet
- Added define_styles method to application helper for workbook styling.
https://issues.umd.edu/browse/LIBITD-LIBITD-526
> LIBITD-526. Modify fields in Excel Export.

- app/controllers/ping_controller.rb
- config/routes.rb
- test/integration/cas_authorization_test.rb
https://issues.umd.edu/browse/LIBITD-691
> LIBITD-691. Add a "ping" service for reporting application availability.

- app/views/reports/_requests_by_department_report_form.html.erb
https://issues.umd.edu/browse/LIBITD-722
> LIBITD-722. Sorted Departments in "Requests by department" report form

- app/controllers/personnel_request_controller.rb
Added a generic "Not Authorized" message that does not display any
details about the requested record.
https://issues.umd.edu/browse/LIBITD-718
> LIBITD-718. "Access Denied" message shows information being denied

- app/assets/javascripts/application.js
- app/views/contractor_requests/_form.html.erb
- app/views/labor_requests/_form.html.erb
- app/views/shared/_form_are_you_sure.erb
- app/views/staff_requests/_form.html.erb
- vendor/assets/javascripts/jquery.are-you-sure.js
https://issues.umd.edu/browse/LIBITD-561
> LIBITD-561. Warning if leaving page that is not saved

- app/helpers/personnel_requests_helper.rb
- app/views/staff_requests/show.html.erb
- test/integration/staff_requests_index_test.rb
- test/integration/staff_requests_show_test.rb
This add employee_name to teh staff_request index table and the view page
https://issues.umd.edu/browse/LIBITD-735
> LIBITD-735 Add employee_name to staff_request index table

- .gitignore
- app/assets/javascripts/application.js
- app/assets/javascripts/personnel_requests.js
- app/views/shared/_index_action_buttons.erb
- app/views/shared/_table_body.html.erb
- app/views/shared/_table_header.html.erb
- vendor/assets/javascripts/jquery.spin.js
- vendor/assets/javascripts/spin.js
Adds a button to index pages of requests that allows for selection and bulk
status updates of record.
https://issues.umd.edu/browse/LIBITD-567
> LIBITD-567 Allow for bulk status changes for Requests

- app/views/shared/_index_action_buttons.erb
Only Admins can update the status so only admins should see that toggle.
https://issues.umd.edu/browse/LIBITD-567
> LIBITD-567 Only admins should see the bulk status update toggle

- .rubocop.yml
- app/assets/javascripts/application.js
- app/assets/javascripts/toggle.es6
- app/assets/stylesheets/home.scss
- app/controllers/organizations_controller.rb
- app/models/archived_request.rb
- app/models/organization.rb
- app/models/request.rb
- app/models/review_status.rb
- app/models/user.rb
- app/views/organizations/_form.erb
- app/views/organizations/index.html.erb
- db/migrate/20170817113652_add_org_toggle.rb
- db/schema.rb
- lib/counter_cache_manager.rb
- lib/tasks/reset_counters.rake
- test/controllers/organizations_controller_test.rb
- test/models/organization_test.rb
- test/test_helper.rb
This makes name, code, parent, organization_type uneditable if there's
records in the archive.
https://issues.umd.edu/browse/LIBITD-926
> LIBITD-926 Make certain fields uneditable if org has archived

- lib/tasks/sample_data.rake
- test/fixtures/archived_requests.yml
- test/fixtures/organizations.yml
- test/fixtures/requests.yml
Fixed failing test by regenerating test data so that there was "consistency" between the department
and unit for a particular request (i.e., that the unit's department matches the department for the
request).
https://issues.umd.edu/browse/LIBITD-970
> LIBITD-970. Request policy scope test is failing on Jenkins

- app/models/contractor_request.rb
- app/models/labor_request.rb
- app/models/request.rb
- test/fixtures/archived_requests.yml
- test/fixtures/requests.yml
- test/models/organization_test.rb
Updated VALID_EMPLOYEE_TYPES for the "LaborRequest" model to:
* Contingent 1
* Faculty Hourly
* Student
to match employee types for v1.2.0 on the production server.
Also updated names of employee types for the "ContractrorRequest" model to:
* Contingent 2
* Contract Faculty
to match employee types for v1.2.0 on the production server.
Regenerated test fixture data requests.yml and archived_requests.yml.
https://issues.umd.edu/browse/LIBITD-984
> LIBITD-984. Fix VALID_EMPLOYEE_TYPES for LaborRequest model

- db/seeds.rb
- lib/from_pre2.rb
- lib/tasks/load_data.rake
This adds an importer to pull in records from the JSON export. A rake task is is added ( db:load_data ) and some seeds are changed to match those in pre-2.0. 
https://issues.umd.edu/browse/LIBITD-977
> LIBITD-977 Add JSON importer to load data from pre-2.0 databases

- db/seeds.rb
- lib/tasks/load_data.rake
- test/fixtures/archived_requests.yml
- test/fixtures/organizations.yml
- test/fixtures/requests.yml
Changed organization data in "seeds.rb" to match organizations on the production server.\
Updated test fixtures with new organizations.
https://issues.umd.edu/browse/LIBITD-998
> LIBITD-998. Update seeds.rb to match organizations on production server

- Gemfile
- Gemfile.lock
- config/database.yml
Needed Postgres configuration for the dev/stage/production servers
https://issues.umd.edu/browse/LIBITD-998
> LIBITD-1000. Update Annual Staffing Request to run on dev/stage/production servers

- app/assets/stylesheets/form.scss
- app/controllers/concerns/personnel_request_controller.rb
- app/controllers/home_controller.rb
- app/helpers/application_helper.rb
- app/models/concerns/flattenable.rb
- app/models/organization.rb
- app/models/request.rb
- app/views/home/show.html.erb
- app/views/layouts/application.html.erb
- app/views/requests/_contractor_request_form.html.erb
- app/views/requests/_edit_form_header.html.erb
- app/views/requests/_form_btns.html.erb
- app/views/requests/_labor_request_form.html.erb
- app/views/requests/_staff_request_form.html.erb
- app/views/requests/index.html.erb
- app/views/requests/index.xlsx.axlsx
- app/views/shared/_index_action_buttons.html.erb
- app/views/users/_role_fields.html.erb
- config/locales/en.yml
- config/routes.rb
- test/integration/index_view_test.rb
- test/integration/read_only_form_test.rb
- test/integration/word_count_test.rb
- test/models/labor_request_test.rb
This is a bulk PR for tickets LIBITD- 
1011,1012,1013,1014,1017,1018,1016,1021,1019,1022
> Libitd 1011

- lib/tasks/load_data.rake
- test/models/labor_request_test.rb
This adds the ability to load user data from a user.json file
https://issues.umd.edu/browse/LIBITD-1001
> LIBITD-1001 Provide mechanism for exporting/importing users

- app/views/home/index.html.erb
- app/views/home/show.html.erb
Current year should display next year since application are submitted
for the next year.
https://issues.umd.edu/browse/LIBITD-1027
> LIBITD-1027 Make "Current Year" display next year

- app/views/requests/index.html.erb
This make the "Update Status" button open the status dropdown.
https://issues.umd.edu/browse/LIBITD-1023
> LIBITD-1023 Make clicking change status button open dropdown

- Gemfile
- Gemfile.lock
- app/views/home/show.html.erb
Updated to use v1.0.1 of umd_lib_style gem.
Also fixed an unclosed "div" tag in app/views/home/show.html.erb, and fixed indentation.
https://issues.umd.edu/browse/LIBITD-1068
> LIBITD-1068. Add Web Accessibility link to Annual Staffing Request

- Gemfile
- Gemfile.lock
- README.md
- test/application_system_test_case.rb
- test/system/department_user_test.rb
- test/system/index_view_test.rb
- test/system/organization_edit_test.rb
- test/system/read_only_form_test.rb
- test/system/unit_user_test.rb
- test/system/word_count_test.rb
- test/test_helper.rb
Converted existing "integration" tests to Rails 5.1 "system" tests.
https://issues.umd.edu/browse/LIBITD-1286
> LIBITD-1286. Convert Annual Staffing integration tests to system tests

- .rubocop.yml
- app/controllers/concerns/personnel_request_controller.rb
- test/controllers/labor_requests_controller_test.rb
https://issues.umd.edu/browse/LIBITD-1282
> FEATURE-1282 Fix multiple update_status feature

- config/environments/development.rb
- config/environments/test.rb
https://issues.umd.edu/browse/LIBITD-1294
> LIBITD-1294 Disable SSL check on dev and test

- app/helpers/application_helper.rb
- test/system/index_view_test.rb
https://issues.umd.edu/browse/LIBITD-1295
> LIBITD-1295 Keep in archive when sorting

- app/views/requests/index.html.erb
- test/application_system_test_case.rb
- test/system/index_view_test.rb
https://issues.umd.edu/browse/LIBITD-1289
> LIBITD-1289 Ensure archive is added to export button

- app/views/home/show.html.erb
Show the organization cutoff dates on the front page.
https://issues.umd.edu/browse/LIBITD-1297
> LIBITD-1297 Show cutoff dates on front page

- app/models/concerns/requestable.rb
- app/models/request.rb
- config/initializers/app_constants.rb
- test/models/labor_request_test.rb
This adds annual_base_pay and the annual_cost to the My Request table
and export.
https://issues.umd.edu/browse/LIBITD-1296
> LIBITD-1296

- app/controllers/home_controller.rb
- app/helpers/application_helper.rb
- app/helpers/request_helper.rb
- config/locales/en.yml
- test/system/index_view_test.rb
Fixed errors that appeared when sorting the following columns:
* Department
* Unit
* Status
* Submitted By
Also changed the "Annual Cost Or Base Pay" column to not be sortable.
https://issues.umd.edu/browse/LIBITD-1305
> LIBITD-1305. Fixed My Requests column sort errors
